server:
  port: 8082
  context-path: /
spring:
  #  thymeleaf:
  #    cache: false
  #    mode: HTML5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdatajpa?characterEncoding=utf8
    username: root
    password: eplugger
    #配置监控统计拦截的filters,去掉后监控界面sql将无法统计，wall ，log4j
    filters: stat
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间（毫秒）
    maxWait: 60000
    #打开PScache，并指定每个PScache连接的大小
    poolPreparedStatments: true
    maxPoolPreparedStatmentPerConnectionSize: 20
    #打开mergeSql功能，开启执行超5秒的sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
    #是否初始化数据库
    initialize: true
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb

#  devtools:
#    restart:
      #热部署生效
#      enabled: true
      #设置重启的目录
      #additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
#      exclude: WEB-INF/**jpa

  session.store-type: none

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
#application:
#  hello: Hello Angel From application
#security:
#    user:
#        name: admin
#        password: admin
#        role: ...